services:
  db:
    image: postgres:16
    container_name: vaultflow-db-1
    environment:
      POSTGRES_DB: securedb
      POSTGRES_USER: secureuser
      POSTGRES_PASSWORD: securepass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secureuser -d securedb"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    image: vaultflow-backend:latest
    container_name: vaultflow-backend-1
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/securedb
      SPRING_DATASOURCE_USERNAME: secureuser
      SPRING_DATASOURCE_PASSWORD: securepass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      VAULTFLOW_CORS_ALLOWED_ORIGINS: http://localhost:4200
      VAULTFLOW_JWT_SECRET: Q3J5cHRvR3JhcGhpY0FscGhhYmV0U2VjcmV0MjA0OEByYW5kb21GZW5jZQ
      VAULTFLOW_JWT_EXP_MINUTES: "60"
      RATELIMIT_LOGIN_PERMINUTE: "20"
      RATELIMIT_LOGIN_BURST: "10"
      RATELIMIT_TRANSFER_PERMINUTE: "60"
      RATELIMIT_TRANSFER_BURST: "20"

      # --- Brevo SMTP (START) ---
      SPRING_MAIL_HOST: smtp-relay.brevo.com
      SPRING_MAIL_PORT: "587"
      SPRING_MAIL_USERNAME: vault11@gmail.com
      SPRING_MAIL_PASSWORD: xsmtpsib-228178305e70bdb1c154b0bfc04d6bdd89b000c20477fc9e60ac020149d4641b-iLmKqe1BRND6LJIP
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      # Optional timeouts (ms)
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT: "5000"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: "5000"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT: "5000"

      # App-level "from" (used by SecurityMailService)
      VAULTFLOW_MAIL_FROM: vault11@gmail.com
      # --- Brevo SMTP (END) ---
    ports:
      - "8080:8080"

  frontend:
    image: vaultflow-frontend:latest
    container_name: vaultflow-frontend-1
    depends_on:
      backend:
        condition: service_started
    ports:
      - "4200:80"

volumes:
  dbdata:
