spring:
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: "98fd6d001@smtp-brevo.com"   # <-- USE THE EXACT BREVO LOGIN EMAIL that owns the SMTP key
    password: "xsmtpsib-e3719499b77c047de2bc7601b6a63d4e8c51005afe8652de6f7e2b7f90c96d8e-rlMXzO47sjYC9ZzX"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
    from: "nadimhamze10@gmail.com"   

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false

  # (Optional) If you prefer to keep DB creds in env vars, leave this commented out.
  # datasource:
  #   url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/securedb}
  #   username: ${SPRING_DATASOURCE_USERNAME:secureuser}
  #   password: ${SPRING_DATASOURCE_PASSWORD:securepass}
  #   driver-class-name: org.postgresql.Driver

server:
  port: ${SERVER_PORT:8080}

vaultflow:
  cors:
    allowed-origins: ${VAULTFLOW_CORS_ALLOWED_ORIGINS:http://localhost:4200}
  jwt:
    secret: ${VAULTFLOW_JWT_SECRET:dev-secret-change-me}
    exp-minutes: ${VAULTFLOW_JWT_EXP_MINUTES:60}

ratelimit:
  login:
    perMinute: ${RATELIMIT_LOGIN_PERMINUTE:20}
    burst: ${RATELIMIT_LOGIN_BURST:10}
  transfer:
    perMinute: ${RATELIMIT_TRANSFER_PERMINUTE:60}
    burst: ${RATELIMIT_TRANSFER_BURST:20}

logging:
  level:
    root: INFO
    org.springframework.mail: DEBUG
    org.springframework.mail.javamail: DEBUG
    com.example.securetransfer.notifications: INFO

